// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function str(prim) {
  return prim;
}

function fizzbuzz(i) {
  var match = i % 3;
  var match$1 = i % 5;
  if (match !== 0) {
    if (match$1 !== 0) {
      return /* Number */3;
    } else {
      return /* Buzz */1;
    }
  } else if (match$1 !== 0) {
    return /* Fizz */0;
  } else {
    return /* FizzBuzz */2;
  }
}

function handleClick(setScore, action) {
  return Curry._1(setScore, (function (score) {
                var match = action === fizzbuzz(score);
                if (match) {
                  return score + 1 | 0;
                } else {
                  return 1;
                }
              }));
}

function button(text, action, setScore) {
  return React.createElement("div", {
              className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded mt-2",
              onClick: (function (param) {
                  return handleClick(setScore, action);
                })
            }, text);
}

function FizzBuzz(Props) {
  var match = React.useState((function () {
          return 1;
        }));
  var setScore = match[1];
  var score = match[0];
  return React.createElement("div", {
              className: "container mx-auto px-2"
            }, React.createElement("div", {
                  className: "max-w-md mx-auto"
                }, React.createElement("div", {
                      className: "font-bold text-6xl text-center pt-10"
                    }, "FizzBuzz"), React.createElement("div", {
                      className: "font-semibold text-center text-6xl text-green-500"
                    }, String(score)), button(String(score), /* Number */3, setScore), button("Fizz", /* Fizz */0, setScore), button("Buzz", /* Buzz */1, setScore), button("FizzBuzz", /* FizzBuzz */2, setScore)));
}

var make = FizzBuzz;

exports.str = str;
exports.fizzbuzz = fizzbuzz;
exports.handleClick = handleClick;
exports.button = button;
exports.make = make;
/* react Not a pure module */
