// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function str(prim) {
  return prim;
}

function fizzbuzz(i) {
  var match = i % 3;
  var match$1 = i % 5;
  if (match !== 0) {
    if (match$1 !== 0) {
      return /* Number */3;
    } else {
      return /* Buzz */1;
    }
  } else if (match$1 !== 0) {
    return /* Fizz */0;
  } else {
    return /* FizzBuzz */2;
  }
}

function handleClick(setScore, action) {
  return Curry._1(setScore, (function (score) {
                var match = action === fizzbuzz(score);
                if (match) {
                  return score + 1 | 0;
                } else {
                  return 1;
                }
              }));
}

function button(text, action, setScore) {
  return React.createElement("div", {
              className: "bg-green-500 text-white font-bold py-2 px-4 shadow-lg rounded mt-2 py-2 px-4 text-lg text-center ",
              onClick: (function (param) {
                  return handleClick(setScore, action);
                })
            }, text);
}

function buttonText(action, number) {
  switch (action) {
    case 0 : 
        return "Fizz";
    case 1 : 
        return "Buzz";
    case 2 : 
        return "FizzBuzz";
    case 3 : 
        return String(number);
    
  }
}

function FizzBuzz(Props) {
  var match = React.useState((function () {
          return 1;
        }));
  var setScore = match[1];
  var score = match[0];
  return React.createElement("div", {
              className: "container mx-auto px-2"
            }, React.createElement("div", {
                  className: "max-w-md mx-auto"
                }, React.createElement("div", {
                      className: "font-bold text-6xl text-center pt-10"
                    }, "FizzBuzz"), React.createElement("div", {
                      className: "font-semibold text-center text-6xl text-green-500"
                    }, String(score)), $$Array.map((function (action) {
                        return button(buttonText(action, score), action, setScore);
                      }), /* array */[
                      /* Number */3,
                      /* Fizz */0,
                      /* Buzz */1,
                      /* FizzBuzz */2
                    ])));
}

var make = FizzBuzz;

exports.str = str;
exports.fizzbuzz = fizzbuzz;
exports.handleClick = handleClick;
exports.button = button;
exports.buttonText = buttonText;
exports.make = make;
/* react Not a pure module */
