// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var FizzBuzz$ReactHooksTemplate = require("./FizzBuzz.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(FizzBuzz$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "app");

/*  Not a pure module */
